limits-service.minimum=10
limits-service.maximum=300

# Data from the microservice-b.properties file has been provided. 
# This file contains configuration properties for a microservice, 
# specifically defining the minimum and maximum limits for a service.
#  The values are set to 10 for minimum and 300 for maximum.   